// src/App.tsx
import React from "react";
import "./App.css";

// 3つのコンポーネントをインポート
import FireworkScene from "./components/FireworkScene";
import MemoryScene from "./components/MemoryScene";
import TextOverlay from "./components/TextOverlay";

function App() {
  return (
    <div className="App">
      {/* 花火シーン */}
      <FireworkScene />

      {/* 思い出シーン */}
      <MemoryScene />

      {/* 詩的なテキストオーバーレイ */}
      <TextOverlay />
    </div>
  );
}

export default App;

// src/App.vue
<template>
  <div class="w-screen h-screen bg-black overflow-hidden relative">
    <FireworkScene />
    <MemoryScene />
    <TextOverlay />
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import FireworkScene from "./components/FireworkScene.vue";
import MemoryScene from "./components/MemoryScene.vue";
import TextOverlay from "./components/TextOverlay.vue";

export default defineComponent({
  name: "App",
  components: {
      FireworkScene,
      MemoryScene,
      TextOverlay,
    },
});
</script>
